[package]
name = "sudoku_solver"
version = "0.1.0"
edition = "2021"
authors = ["Hakan Vardar"]
description = "Sudoku Solver"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
