[package]
name = "sudoku_solver"
version = "0.1.0"
edition = "2021"
authors = ["Hakan Vardar"]
description = "Sudoku Solver"
license = "MIT"
repository = "https://github.com/HakanVardarr/sudoku_solver"

[lib]
path = "src/lib.rs"

[dependencies]
